export const SET_AUTHENTIFICATION = "SET_AUTHENTIFICATION";
export const ADD_RESSOURCE = "ADD_RESSOURCE";
export const GET_SPECIAL_RESOURCE = "GET_SPECIAL_RESOURCE";

export const PARSE_ERROR = "PARSE_ERROR";
export const RESET_ERROR = "RESET_ERROR";
